<?php
namespace Intelink;
defined('ABSPATH') || exit;

final class Store {
    public static function table(string $name): string { global $wpdb; return $wpdb->prefix . 'ib_' . $name; }
    public static function install(): void {
        global $wpdb;
        if(!function_exists('openssl_encrypt')) throw new \RuntimeException('Intelink Booking requires the PHP OpenSSL extension.');
        require_once ABSPATH . 'wp-admin/includes/upgrade.php';
        $charset = $wpdb->get_charset_collate();
        $schemas = [
            'services'=>"id bigint unsigned NOT NULL AUTO_INCREMENT, name varchar(190) NOT NULL, description longtext NOT NULL, image_id bigint unsigned NOT NULL DEFAULT 0, category_id bigint unsigned NOT NULL DEFAULT 0, price bigint NOT NULL DEFAULT 0, sale_price bigint DEFAULT NULL, duration int NOT NULL DEFAULT 30, buffer_before int NOT NULL DEFAULT 0, buffer_after int NOT NULL DEFAULT 0, capacity int NOT NULL DEFAULT 1, payment_required tinyint NOT NULL DEFAULT 1, deposit_type varchar(20) NOT NULL DEFAULT 'full', deposit_value decimal(12,2) NOT NULL DEFAULT 0, status varchar(20) NOT NULL DEFAULT 'draft', config longtext NOT NULL, PRIMARY KEY  (id), KEY public_services (status,category_id)",
            'service_categories'=>"id bigint unsigned NOT NULL AUTO_INCREMENT, name varchar(190) NOT NULL, slug varchar(190) NOT NULL, PRIMARY KEY  (id), UNIQUE KEY slug (slug)",
            'staff'=>"id bigint unsigned NOT NULL AUTO_INCREMENT, name varchar(190) NOT NULL, email varchar(190) NOT NULL DEFAULT '', phone varchar(60) NOT NULL DEFAULT '', image_id bigint unsigned NOT NULL DEFAULT 0, capacity int NOT NULL DEFAULT 1, status varchar(20) NOT NULL DEFAULT 'active', config longtext NOT NULL, PRIMARY KEY  (id)",
            'staff_services'=>"id bigint unsigned NOT NULL AUTO_INCREMENT, staff_id bigint unsigned NOT NULL, service_id bigint unsigned NOT NULL, PRIMARY KEY  (id), UNIQUE KEY assignment (staff_id,service_id)",
            'customers'=>"id bigint unsigned NOT NULL AUTO_INCREMENT, email varchar(190) NOT NULL, first_name varchar(100) NOT NULL, last_name varchar(100) NOT NULL, phone varchar(60) NOT NULL, country varchar(100) NOT NULL DEFAULT '', city varchar(100) NOT NULL DEFAULT '', address text NOT NULL, created_at datetime NOT NULL, PRIMARY KEY  (id), UNIQUE KEY email (email)",
            'appointments'=>"id bigint unsigned NOT NULL AUTO_INCREMENT, reference varchar(50) NOT NULL, request_key varchar(64) NOT NULL, token_hash varchar(64) NOT NULL, customer_id bigint unsigned NOT NULL, staff_id bigint unsigned NOT NULL DEFAULT 0, starts_at datetime NOT NULL, ends_at datetime NOT NULL, busy_start datetime NOT NULL, busy_end datetime NOT NULL, status varchar(30) NOT NULL, payment_status varchar(30) NOT NULL DEFAULT 'pending', currency varchar(3) NOT NULL, subtotal bigint NOT NULL, discount bigint NOT NULL DEFAULT 0, tax bigint NOT NULL DEFAULT 0, total bigint NOT NULL, due bigint NOT NULL, paid bigint NOT NULL DEFAULT 0, expires_at datetime DEFAULT NULL, snapshot longtext NOT NULL, notes text NOT NULL, created_at datetime NOT NULL, updated_at datetime NOT NULL, PRIMARY KEY  (id), UNIQUE KEY reference (reference), UNIQUE KEY request_key (request_key), KEY availability (status,busy_start,busy_end), KEY customer (customer_id), KEY staff_schedule (staff_id,busy_start), KEY expiration (status,expires_at)",
            'appointment_meta'=>"id bigint unsigned NOT NULL AUTO_INCREMENT, appointment_id bigint unsigned NOT NULL, meta_key varchar(100) NOT NULL, meta_value longtext NOT NULL, PRIMARY KEY  (id), KEY appointment (appointment_id,meta_key)",
            'availability'=>"id bigint unsigned NOT NULL AUTO_INCREMENT, name varchar(190) NOT NULL, scope varchar(20) NOT NULL DEFAULT 'business', owner_id bigint unsigned NOT NULL DEFAULT 0, weekday int NOT NULL DEFAULT 1, opens varchar(5) NOT NULL DEFAULT '09:00', closes varchar(5) NOT NULL DEFAULT '17:00', breaks text NOT NULL, special_date varchar(10) NOT NULL DEFAULT '', PRIMARY KEY  (id), KEY schedule (scope,owner_id,weekday)",
            'blocked_dates'=>"id bigint unsigned NOT NULL AUTO_INCREMENT, name varchar(190) NOT NULL, scope varchar(20) NOT NULL DEFAULT 'business', owner_id bigint unsigned NOT NULL DEFAULT 0, date_from date NOT NULL, date_to date NOT NULL, PRIMARY KEY  (id), KEY dates (date_from,date_to)",
            'payments'=>"id bigint unsigned NOT NULL AUTO_INCREMENT, reference varchar(64) NOT NULL, appointment_id bigint unsigned NOT NULL, provider varchar(30) NOT NULL, mode varchar(10) NOT NULL DEFAULT 'test', amount bigint NOT NULL, currency varchar(3) NOT NULL, status varchar(30) NOT NULL DEFAULT 'pending', external_id varchar(190) NOT NULL DEFAULT '', checkout_url text NOT NULL, refunded bigint NOT NULL DEFAULT 0, created_at datetime NOT NULL, paid_at datetime DEFAULT NULL, PRIMARY KEY  (id), UNIQUE KEY reference (reference), KEY appointment (appointment_id), KEY revenue (status,paid_at)",
            'payment_events'=>"id bigint unsigned NOT NULL AUTO_INCREMENT, event_key varchar(190) NOT NULL, payment_id bigint unsigned NOT NULL DEFAULT 0, event_type varchar(50) NOT NULL, payload longtext NOT NULL, created_at datetime NOT NULL, PRIMARY KEY  (id), UNIQUE KEY event_key (event_key)",
            'email_templates'=>"id bigint unsigned NOT NULL AUTO_INCREMENT, event varchar(50) NOT NULL, audience varchar(20) NOT NULL DEFAULT 'customer', enabled tinyint NOT NULL DEFAULT 1, subject varchar(250) NOT NULL, body longtext NOT NULL, recipient varchar(190) NOT NULL DEFAULT '', PRIMARY KEY  (id), UNIQUE KEY template (event,audience)",
            'notification_logs'=>"id bigint unsigned NOT NULL AUTO_INCREMENT, event_key varchar(190) NOT NULL, appointment_id bigint unsigned NOT NULL, template_id bigint unsigned NOT NULL, status varchar(20) NOT NULL DEFAULT 'queued', attempts int NOT NULL DEFAULT 0, last_error text NOT NULL, created_at datetime NOT NULL, sent_at datetime DEFAULT NULL, PRIMARY KEY  (id), UNIQUE KEY event_key (event_key), KEY queue (status,attempts)",
            'custom_fields'=>"id bigint unsigned NOT NULL AUTO_INCREMENT, name varchar(100) NOT NULL, label varchar(190) NOT NULL, type varchar(30) NOT NULL DEFAULT 'text', placeholder varchar(190) NOT NULL DEFAULT '', required tinyint NOT NULL DEFAULT 0, sort_order int NOT NULL DEFAULT 0, default_value text NOT NULL, options text NOT NULL, rules text NOT NULL, enabled tinyint NOT NULL DEFAULT 1, PRIMARY KEY  (id), UNIQUE KEY field_name (name)",
            'coupons'=>"id bigint unsigned NOT NULL AUTO_INCREMENT, code varchar(100) NOT NULL, type varchar(20) NOT NULL DEFAULT 'percent', value decimal(12,2) NOT NULL DEFAULT 0, expires_on varchar(10) NOT NULL DEFAULT '', max_uses int NOT NULL DEFAULT 0, uses int NOT NULL DEFAULT 0, enabled tinyint NOT NULL DEFAULT 1, PRIMARY KEY  (id), UNIQUE KEY code (code)",
        ];
        foreach ($schemas as $table=>$schema) dbDelta('CREATE TABLE '.self::table($table).' ('.str_replace(', ', ",\n", $schema).") ENGINE=InnoDB $charset;");
        foreach(array_keys($schemas) as $table) { $info=$wpdb->get_row($wpdb->prepare('SHOW TABLE STATUS WHERE Name=%s',self::table($table)),ARRAY_A); if(!$info || strtoupper($info['Engine'])!=='INNODB') throw new \RuntimeException('Intelink Booking requires InnoDB tables. Database setup did not complete.'); }
        $role=get_role('administrator'); if ($role) $role->add_cap('manage_intelink_booking');
        if (!get_option('ib_settings')) add_option('ib_settings', self::defaults(), '', false);
        if (!self::all('availability')) for ($d=1;$d<=5;$d++) self::insert('availability', ['name'=>'Business hours','scope'=>'business','owner_id'=>0,'weekday'=>$d,'opens'=>'09:00','closes'=>'17:00','breaks'=>'[]','special_date'=>'']);
        Notifications::seed(); update_option('ib_version', IB_VERSION, false);
    }
    public static function defaults(): array { return ['business_name'=>get_bloginfo('name'),'business_email'=>get_option('admin_email'),'business_phone'=>'','help_hours'=>'','business_address'=>'','logo_id'=>0,'timezone'=>wp_timezone_string(),'currency'=>'NGN','primary'=>'#008b73','accent'=>'#eaf5ef','multiple_services'=>0,'staff_selection'=>0,'guest_booking'=>1,'manual_approval'=>0,'slot_interval'=>30,'min_notice'=>120,'max_days'=>90,'capacity'=>20,'cancellation_hours'=>24,'reschedule_hours'=>24,'reservation_minutes'=>30,'tax_percent'=>0,'payment_mode'=>'full','enabled_methods'=>['pay_later'],'mode'=>'test','bank_name'=>'','bank_account'=>'','bank_number'=>'','payment_instructions'=>'','sender_name'=>get_bloginfo('name'),'sender_email'=>get_option('admin_email'),'reminder_hours'=>24,'date_format'=>get_option('date_format'),'time_format'=>get_option('time_format')]; }
    public static function settings(): array { return array_merge(self::defaults(), (array)get_option('ib_settings', [])); }
    public static function tz(): \DateTimeZone { return new \DateTimeZone(self::settings()['timezone']); }
    public static function now(): string { return gmdate('Y-m-d H:i:s'); }
    public static function all(string $table, string $where='1=1', array $args=[]): array { global $wpdb; $q='SELECT * FROM '.self::table($table).' WHERE '.$where; return $wpdb->get_results($args ? $wpdb->prepare($q, ...$args) : $q, ARRAY_A) ?: []; }
    public static function get(string $table, int $id): ?array { return self::all($table,'id=%d',[$id])[0] ?? null; }
    public static function insert(string $table, array $data): int { global $wpdb; Schedule::reset(); if (false===$wpdb->insert(self::table($table),$data)) throw new \RuntimeException('Database write failed.'); return (int)$wpdb->insert_id; }
    public static function update(string $table, int $id, array $data): void { global $wpdb; Schedule::reset(); if (false===$wpdb->update(self::table($table),$data,['id'=>$id])) throw new \RuntimeException('Database update failed.'); }
    public static function json($value): array { return is_array($value) ? $value : (json_decode((string)$value,true) ?: []); }
    public static function digits(string $currency): int { return in_array(strtoupper($currency),['JPY','KRW','VND','CLP','XOF','XAF','RWF','UGX','GNF','BIF','DJF','KMF','PYG','VUV']) ? 0 : (in_array(strtoupper($currency),['BHD','KWD','OMR','JOD','TND']) ? 3 : 2); }
    public static function minor($value): int { return (int)round((float)$value * 10**self::digits(self::settings()['currency'])); }
    public static function money(int $amount, ?string $currency=null): string { $currency=$currency ?: self::settings()['currency']; return $currency.' '.number_format($amount/10**self::digits($currency),self::digits($currency)); }
    public static function atomic(callable $fn) {
        global $wpdb; $key='ib_'.md5(DB_NAME.self::table('appointments'));
        if ((int)$wpdb->get_var($wpdb->prepare('SELECT GET_LOCK(%s, 10)',$key))!==1) throw new \RuntimeException('Booking system is busy. Please retry.');
        Schedule::reset(); $wpdb->query('START TRANSACTION');
        try { $result=$fn(); if (false===$wpdb->query('COMMIT')) throw new \RuntimeException('Commit failed.'); return $result; }
        catch (\Throwable $e) { $wpdb->query('ROLLBACK'); throw $e; }
        finally { $wpdb->get_var($wpdb->prepare('SELECT RELEASE_LOCK(%s)',$key)); }
    }
    public static function history(int $id,string $message): void { self::insert('appointment_meta',['appointment_id'=>$id,'meta_key'=>'history','meta_value'=>wp_json_encode(['at'=>self::now(),'user'=>get_current_user_id(),'message'=>$message])]); }
}
